### ISSUE TITLE
[W10] problem pin position

### ISSUE THREAD

**Issue by a-iafrate** [inthehand/Forms.Maps.Platform.WinRT#4]
Hi
i have added a click function to map to set pin on click position.
when i add the pin to this point the pin is set with top left corner on this point and not at the center of the bottom.

thanks for your work!!

**Comment by peterfoot** [comment]
Hi, thanks for your feedback. I've fixed this in the code now - required setting the NormalizerAnchorPoint for the pushpin icon. I'll update the NuGet package shortly.

**Comment by a-iafrate** [comment]
thanks for your work :D
