### ISSUE TITLE
[UWP] latest version 2.0.60222.0-pre not work

### ISSUE THREAD

**Issue by a-iafrate** [inthehand/Forms.Maps.Platform.WinRT#6]
Hi,
i try latest nuget pre release package but don't work, when i launch the app i obtain the error

Could not load type 'InTheHand.Forms.Maps.Platform.UWP.MapRenderer' from assembly 'InTheHand.Forms.Maps.Platform.Windows, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'.

if i go back to 2.0.1216 it's all ok

thanks for your work :D

**Comment by peterfoot** [comment]
Resolved in 2.0.60301

**Comment by a-iafrate** [comment]
Thanks, i have tried this version it's all ok but MoveToRegion not work in this release :/
