### ISSUE TITLE
[UWP] Pin.clicked not works

### ISSUE THREAD

**Issue by a-iafrate** [inthehand/Forms.Maps.Platform.WinRT#7]
Hi
With lastest stable version on github the pin.clicked don't works.

thanks for your work :D

**Comment by peterfoot** [comment]
Fixed in latest checkin. NuGet package to follow.

**Comment by a-iafrate** [comment]
Thanks :D

**Comment by a-iafrate** [comment]
Some news about new nuget package with this fix?

**Comment by peterfoot** [comment]
Should be up now as version 2.0.60301
